services:
  eureka-server:
    build: ../eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api-gateway-concessionaria:
    build: ../api-gateway-concessionaria
    container_name: api-gateway-concessionaria
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
          condition: service_healthy

  funcionario-service:
    build: ../api-funcionarios
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
      funcionario-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://funcionario-db:5432/funcionarios_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  cliente-service:
    build: ../api-clientes
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
      cliente-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cliente-db:5432/clientes_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  veiculo-service:
    build: ../api-veiculos
    ports:
      - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_healthy
      veiculo-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://veiculo-db:5432/veiculos_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  venda-service:
    build: ../api-vendas
    ports:
      - "8084:8084"
    depends_on:
      eureka-server:
        condition: service_healthy
      venda-db:
        condition: service_started
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    - SPRING_DATASOURCE_URL=jdbc:postgresql://venda-db:5432/vendas_db
    - SPRING_DATASOURCE_USERNAME=admin
    - SPRING_DATASOURCE_PASSWORD=admin

  auth-service:
    build: ../api-auth
    ports:
      - "8085:8085"
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auths_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  cliente-db:
    image: postgres:14
    container_name: cliente-db
    environment:
      - POSTGRES_DB=clientes_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - cliente-data:/var/lib/postgresql/data

  funcionario-db:
    image: postgres:14
    container_name: funcionario-db
    environment:
      - POSTGRES_DB=funcionarios_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - funcionario-data:/var/lib/postgresql/data

  veiculo-db:
    image: postgres:14
    container_name: veiculo-db
    environment:
      - POSTGRES_DB=veiculos_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - veiculo-data:/var/lib/postgresql/data

  venda-db:
    image: postgres:14
    container_name: venda-db
    environment:
      - POSTGRES_DB=vendas_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - venda-data:/var/lib/postgresql/data

  auth-db:
    image: postgres:14
    container_name: auth-db
    environment:
      - POSTGRES_DB=auths_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - auth-data:/var/lib/postgresql/data

volumes:
  cliente-data:
  funcionario-data:
  veiculo-data:
  venda-data:
  auth-data:
